language: node_js
node_js:
  - 8
sudo: false
before_script:
  - npm run build
script:
  - npm run cover-test
after_success:
  - echo "repo_token: $coveralls_repo_token" >.coveralls.yml
  - npm run cover-publish
